### ISSUE TITLE
Convert on all values in multi select strings

### ISSUE THREAD

**Issue by JJscott** [brunohgv/vs-code-string-converter#10]
When selecting more than one string using multiple cursors, I would expect the behavior to be that each selected string would eb converted using the appropriate conversion (e.g. Camel to Snake)

Currently, if you select each of `tableOne`, `tableTwo` and `tableThree` using multi select:

```
TRUNCATE TABLE tableOne;
TRUNCATE TABLE tableTwo;
TRUNCATE TABLE tableThree;
```

And convert using `Camel to Snake`, you'll get:

```
TRUNCATE TABLE table_one;
TRUNCATE TABLE tableTwo;
TRUNCATE TABLE tableThree;
```

whereas, I would expect:

```
TRUNCATE TABLE table_one;
TRUNCATE TABLE table_two;
TRUNCATE TABLE table_three;
```

**Comment by brunohgv** [comment]
Hi, @JJscott. 
Thanks for sharing this issue.
I agree with you. I'll be working on this task.

**Comment by brunohgv** [comment]
Hello @JJscott .
The multiselect support was already implemented and deployed :D
Soon it will be available in the store (It can take a few minutes).

Thanks for contributing to this project by submitting an issue!
