### ISSUE TITLE
Add functions to converto only TO without FROM identifier

### ISSUE THREAD

**Issue by brunohgv** [brunohgv/vs-code-string-converter#7]
Actually all functions are described as "Type To Type".

It would be good to automatically identify and just select the To identified.

Ex: 
implement *toKebab* instead of *camelToKebab*, *titleToKebab*, *snakeToKebab*

**Comment by ccsCoder** [comment]
Raised the following PR. Please take a look:

https://github.com/brunohgv/vs-code-string-converter/pull/9

**Comment by ccsCoder** [comment]
@brunohgv when you get some time could you please look at the above pr?

**Comment by brunohgv** [comment]
Hi, @ccsCoder. The PR was approved.

Thanks for the contribution!
